import type { Metadata } from 'next'
import Link from 'next/link'


export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
		<>
			<h1>About us</h1>
			<ul>
				<li><Link href='/about/team'>Team</Link></li>
				<li><Link href='/about/projects'>Projects</Link></li>
			</ul>
			{children}
		</>
  )
}
